spring:
  datasource:
    url: jdbc:mysql://${SPRING_DATABASE_HOST}:3306/${SPRING_DATABASE_SCHEMA}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

discord:
  webhook:
    url: {DISCORD_WEBHOOK_URL}