spring:
  profiles:
    active: local

---
# local profile
# application-local.yml
spring:
  config:
    activate:
      on-profile: local

---
# dev profile
# application-dev.yml
spring:
  config:
    activate:
      on-profile: dev
